Revert "Pin python3-pip to prevent "AttributeError: module 'tarfile' has no attribute 'data_filter'","
This reverts commit b801d7d9f2190d7dd7b7fc9b00db0f37385a91a8.